/*
 * Copyright (c) 2001-2007, TIBCO Software Inc.
 * Use, modification, and distribution subject to terms of license.
 */
jsx3.require("jsx3.gui.Block");jsx3.Class.defineClass("jsx3.gui.Column",jsx3.gui.Block,null,function(s,g){s.DEFAULTWIDTH=100;s.DEFAULTCELLCLASSLIST="jsx30column_c1";s.DEFAULTCELLCLASSGRID="jsx30column_c3";s.TYPETEXT="text";s.TYPENUMBER="number";s.FIXED=0;s.RESIZEABLE=1;s.RESIZABLE=1;s.zD="<xsl:choose><xsl:when test=\"@path@ and not(@path@='')\"><xsl:value-of select=\"@path@\"/></xsl:when><xsl:otherwise>&#160;</xsl:otherwise></xsl:choose>";s.EU=jsx3.resolveURI("jsx:///images/list/sort_asc.gif");s.Y2=jsx3.resolveURI("jsx:///images/list/sort_desc.gif");jsx3.html.loadImages(s.EU,s.Y2);s.IY="&#160;";s.VALIGNTOP="top";s.VALIGNMIDDLE="middle";g.init=function(c,b,q,p){this.jsxsuper(c,null,null,q,null,b);if(p!=null)this.setPath(p);};g.onSetParent=function(d){return jsx3.gui.List&&d instanceof jsx3.gui.List;};g.onDestroy=function(a){return this.doEvent("jsxdestroy",{objPARENT:a});};g.getDataType=function(){return this.jsxdatatype==null?"text":this.jsxdatatype;};g.setDataType=function(i){this.jsxdatatype=i;return this;};g.getEditMask=function(){return this.jsxmask==null?null:this.jsxmask;};g.setEditMask=function(b){this.jsxmask=b;return this;};g.getResizable=function(){return this.jsxresize==null?1:this.jsxresize;};g.setResizable=function(a){this.jsxresize=a;return this;};g.getPath=function(){return this.jsxpath==null?"@jsxid":this.jsxpath;};g.setPath=function(e){this.jsxpath=e;return this;};g.getSortPath=function(){return this.jsxsortpath!=null?this.jsxsortpath:this.getPath();};g.setSortPath=function(b){this.jsxsortpath=b;return this;};g.getWrap=function(){return this.jsxwrap==null?0:this.jsxwrap;};g.setWrap=function(d){this.jsxwrap=d;return this;};g.getVAlign=function(){return this.jsxvalign==null?s.VALIGNTOP:this.jsxvalign;};g.setVAlign=function(j){this.jsxvalign=j;return this;};g.Vd=function(){};g.paint=function(p,o){this.applyDynamicProperties();var
Kb=this.getParent();var
Rb="";if(Kb.getResizable()){var
Hb=Kb.Le();var
Ac=Hb.indexOf(this);if(Ac!=0&&Hb[Ac-1].getResizable()||p&&Hb[Hb.length-1].getResizable())Rb="<span "+Kb.cn("mousedown","de")+' style="" class="jsx30column_anchor">&#160;</span>';}if(p){return '<td  unselectable="on"  class="jsx30column_cell" style="position:relative;padding:0px;" width="*" ><div style="white-space:nowrap;position:relative;height:100%;width:100%;padding:0px;">'+Rb+"&#160;</div></td>";}else{var
yb=this.cn("mouseup","ZY",0);if(Kb.getCanReorder())yb=yb+Kb.cn("mousedown","ph");else if(Kb.getCanSort()!=0&&this.getCanSort()!=0)yb=yb+Kb.cn("click","Jh");var
gc=o==null?"":"background-image:url("+(o=="ascending"?s.EU:s.Y2)+");background-repeat:no-repeat;background-position:99% center;";var
Gc=this.getWrap()?"":"overflow-x:hidden;white-space:nowrap;text-overflow:ellipsis;";var
P=this.getVAlign()==s.VALIGNTOP?Kb._c():"";return '<td cellindex="'+this.getChildIndex()+'" id="'+this.getId()+'" unselectable="on" '+yb+this.Lj()+' class="jsx30column_cell" style="padding-left:0px;position:relative;'+this.Nh(p)+this.Dg()+this.Eo()+this.Ak()+this.Wm()+this.Ho()+this.paintCSSWidth()+this.xp()+gc+this.ji()+'" '+this.fo()+'><div style="'+P+Gc+'position:relative;height:100%;width:100%;padding-left:4px;vertical-align:middle;">'+Rb+"<div>"+this.im()+"</div>"+"</div></td>";}};g.repaint=function(){this.getParent().resetXslCacheData();this.getParent().repaintHead();this.getParent().repaintBody();};g.Nh=function(q){return !this.getCursor()||q?"cursor:default;":"cursor:"+this.getCursor()+";";};g.im=function(){return this.getText()?this.getText():s.IY;};g.Lj=function(r){if(r)return ' width="*"';return ' width="'+(this.getWidth()?this.getWidth():s.DEFAULTWIDTH)+'"';};g.paintCSSWidth=function(m){if(m)return "";var
Jc=this.getWidth()?this.getWidth():s.DEFAULTWIDTH;if(!isNaN(Jc))Jc=Jc+"px";return "width:"+Jc+";";};g.Wg=function(){return this.getClassName()?this.getClassName():jsx3.gui.Grid&&this.getParent() instanceof jsx3.gui.Grid?s.DEFAULTCELLCLASSGRID:s.DEFAULTCELLCLASSLIST;};g.getXSLString=function(r){return this.jsxxsl;};g.setXSLString=function(q){if(jsx3.util.strEmpty(q)){delete this.jsxxsl;}else this.jsxxsl=q;return this;};g.paintXSLString=function(n){var
Sb=this.getPath()?'<xsl:value-of select="'+this.getPath()+'"/>':"";if(this.getParent().getWrap()==1){var
kc="";var
tc="";}else{var
kc="<nobr>";var
tc="</nobr>";}if(n){return '<td style="position:relative;" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" unselectable="on" width="*" class="'+this.Wg()+'">&#160;</td>';}else if(jsx3.gui.Grid&&this.getParent() instanceof jsx3.gui.Grid){var
I;var
bb=(I=this.getEditMask())==null?"":' jsxmask="'+I+'" ';return '<td valign="top" '+this.getParent().vo()+bb+this.Lj()+this.cn("focus","Uo")+this.getParent().cn("blur","doBlurItem")+' style="position:relative;'+this.Ho()+';" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" unselectable="on" '+' class="'+this.Wg()+'">'+kc+this.MJ()+tc+"</td>";}else return "<td"+this.Lj()+' style="position:relative;'+this.Ho()+'" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" unselectable="on"'+' class="'+this.Wg()+'">'+kc+this.MJ()+tc+"</td>";};g.Uo=function(f,l){this.getParent().doFocusItem(l);};g.MJ=function(){if(this.getXSLString()){var
Z=this.getPath();if(Z)return this.getXSLString().doReplace("@path@",Z);else return this.getXSLString();}else{var
Z=this.getPath();if(Z)return s.zD.doReplace("@path@",Z);else return "";}};g.getCanSort=function(){return this.jsxsort==null?1:this.jsxsort;};g.setCanSort=function(b){this.jsxsort=b;return this;};g.getMaskProperties=function(){return jsx3.gui.Block.MASK_NO_EDIT;};s.getVersion=function(){return "3.0.00";};});jsx3.gui.Column.prototype.getResizeable=jsx3.gui.Column.prototype.getResizable;jsx3.gui.Column.prototype.setResizeable=jsx3.gui.Column.prototype.setResizable;jsx3.Column=jsx3.gui.Column;
