/*
 * Copyright (c) 2001-2007, TIBCO Software Inc.
 * Use, modification, and distribution subject to terms of license.
 */
jsx3.require("jsx3.gui.Painted","jsx3.gui.Interactive");jsx3.Class.defineClass("jsx3.gui.Sound",jsx3.gui.Painted,[jsx3.gui.Interactive],function(p,e){p.Vv={};p.Vv.ex=function(k){return typeof k.GetQuickTimeVersion!="undefined";};p.Vv.wM=function(a){a.Play();};p.Vv.HT=function(k){k.Stop();};p.Vv.K_=function(g){g.Stop();g.Rewind();};p.Vv.aN=function(o){return o.GetDuration()/o.GetTimeScale();};p.Vv.bB=function(a){return a.GetTime()/a.GetTimeScale();};p.Vv.mL=function(f,i){f.SetTime(i*f.GetTimeScale());};p.Vv.g1=function(c,s){c.SetVolume(this.e0(s));};p.Vv.e0=function(g){return Math.round(g*255/100);};p.Vv.toString=function(){return "Apple QuickTime";};p.Vv.qK=function(b){return this+" "+b.GetQuickTimeVersion();};p.Vz={};p.Vz.ex=function(d){return typeof d.GetVersionInfo!="undefined";};p.Vz.wM=function(a){if(a.CanPlay()){a.DoPlay();if(a.jsxlength==null){a.jsxlength=a.GetLength();a.SetPreFetch(false);}}};p.Vz.HT=function(c){if(c.CanPause())c.DoPause();};p.Vz.K_=function(k){if(k.CanStop())k.DoStop();};p.Vz.aN=function(m){if(m.GetPlayState()!=0||m.GetPreFetch()){return m.GetLength()/1000;}else return m.jsxlength!=null?m.jsxlength/1000:Number.NaN;};p.Vz.bB=function(a){return a.GetPosition()/1000;};p.Vz.mL=function(i,l){if(i.GetPlayState()!=0){i.SetPosition(l*1000);}else{i.DoPlay();i.SetPosition(l*1000);i.DoPause();}};p.Vz.YI=function(h){return h.GetPlayState()==3;};p.Vz.g1=function(b,r){b.SetVolume(this.e0(r));};p.Vz.e0=function(a){return Math.round(a);};p.Vz.toString=function(){return "RealPlayer";};p.Vz.qK=function(n){return this+" "+n.GetVersionInfo();};p.W1={};p.W1.ex=function(f){return typeof f.GetMediaInfoString!="undefined";};p.W1.wM=function(a){a.Play();};p.W1.HT=function(j){j.Pause();};p.W1.K_=function(g){g.Stop();};p.W1.aN=function(a){return a.Duration;};p.W1.bB=function(q){return q.CurrentPosition;};p.W1.mL=function(c,f){c.CurrentPosition=f;};p.W1.YI=function(m){return m.PlayState==2;};p.W1.g1=function(b,r){b.Volume=this.e0(r);};p.W1.e0=function(n){return Math.max(-10000,Math.round(2500*Math.log(n*100)/Math.LN10-10000));};p.W1.toString=function(){return "Windows Media Player";};p.W1.qK=function(j){if(this.VERSION==null)try{this.VERSION="Unknown Version";if(window.ActiveXObject){this.ACTIVEX=new
ActiveXObject("WMPlayer.OCX.7");this.VERSION=this.ACTIVEX.versionInfo;}}catch(Kc){}return this+" "+this.VERSION;};p.Gr={};p.Gr.ex=function(j){return true;};p.Gr.wM=function(o){if(typeof o.Play!="undefined")o.Play();};p.Gr.HT=function(i){if(typeof i.Pause!="undefined")i.Pause();};p.Gr.K_=function(k){if(typeof k.Stop!="undefined")k.Stop();};p.Gr.aN=function(k){return Number.NaN;};p.Gr.bB=function(g){return Number.NaN;};p.Gr.mL=function(a,d){};p.Gr.YI=function(f){return false;};p.Gr.g1=function(k,h){if(typeof k.SetVolume!="undefined")k.SetVolume(this.e0(h));};p.Gr.e0=function(r){return Math.round(r);};p.Gr.toString=function(){return "Generic";};p.Gr.qK=function(d){return this.toString();};p._F=[p.Vv,p.Vz,p.W1,p.Gr];e.jsxurl=null;e.jsxvolume=50;e._jsxTv=null;e.init=function(s,b){this.jsxsuper(s);this.jsxurl=b;};e.getURL=function(){return this.jsxurl;};e.setURL=function(j){this.jsxurl=j;return this;};e.getVolume=function(){return this.jsxvolume;};e.Lv=function(){var
x=this.jsxvolume!=null?this.jsxvolume:this.prototype.jsxvolume;return this.Cv().e0(x);};e.setVolume=function(q){this.jsxvolume=q==null?null:Math.max(0,Math.min(100,q));var
Hb=this.getRendered();if(Hb!=null){var
P=this.jsxvolume!=null?this.jsxvolume:this.prototype.jsxvolume;this.Cv().g1(Hb,P);}return this;};e.play=function(){var
Mc=this.getRendered();if(Mc!=null)this.Cv().wM(Mc);};e.pause=function(){var
H=this.getRendered();if(H!=null)this.Cv().HT(H);};e.rewind=function(){var
O=this.getRendered();if(O!=null)this.Cv().K_(O);};e.getLength=function(){var
db=this.getRendered();return db!=null?this.Cv().aN(db):Number.NaN;};e.getPosition=function(){var
dc=this.getRendered();return dc!=null?this.Cv().bB(dc):Number.NaN;};e.setPosition=function(c){var
tc=this.getRendered();if(tc!=null)this.Cv().mL(tc,c);};e.getPluginVersion=function(){var
hb=this.getRendered();if(hb!=null)try{return this.Cv().qK(hb);}catch(Kc){}return this.Cv().toString();};e.Cv=function(){if(this._jsxTv!=null)return this._jsxTv;var
mc=this.getRendered();if(mc!=null){for(var
Rb=0;Rb<p._F.length;Rb++){var
w=p._F[Rb];if(w.ex(mc)){this._jsxTv=w;break;}}return this._jsxTv;}else return p.Gr;};e.paint=function(){this.applyDynamicProperties();var
Z=this.Lv();return '<embed id="'+this.getId()+'" name="'+this.getId()+'" class="jsx30sound" src="'+this.getUriResolver().resolveURI(this.getURL())+'" enablejavascript="true" autostart="false" '+this.renderAttributes()+' volume="'+Z+'" prefetch="true" unselectable="on"/>';};e.onDestroy=function(h){this.jsxsuper(h);this.doEvent("jsxdestroy",{objPARENT:h});};});
