/*
 * Copyright (c) 2001-2007, TIBCO Software Inc.
 * Use, modification, and distribution subject to terms of license.
 */
jsx3.require("jsx3.gui.Block");jsx3.Class.defineClass("jsx3.gui.Window",jsx3.app.Model,null,function(a,n){var
Y=jsx3.Exception;var
cb=jsx3.util.Logger;var
Rb=cb.getLogger(a.jsxclass.getName());a.j0=new
jsx3.net.URI("jsx3.gui.window.html");a.KH=new
jsx3.net.URI("jsx3.gui.window.xhtml");if(jsx3.CLASS_LOADER.IE){a.KM="screenLeft";a.xP="screenTop";}else{a.KM="screenX";a.xP="screenY";}a.DID_OPEN="open";a.WILL_CLOSE="close";a.DID_FOCUS="focus";a.DID_RESIZE="resize";a.PARENT_DID_CLOSE="pclose";n.jsxwidth=400;n.jsxheight=300;n.jsxresizable=0;n.jsxscrollable=0;n.jsxdependent=1;n.jsxtitle="";n._jsxwindow=null;n._jsxpC=null;n.init=function(b){this.jsxsuper(b);};n.open=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){throw new
Y(jsx3._msg("gui.win.op",this));}else{var
R=jsx3.util.strEndsWith(jsx3.app.Browser.getLocation().getPath().toLowerCase(),".xhtml")?a.KH:a.j0;var
tc=window.open(R.toString(),this.getId().replace(/\./g,""),"directories=no,location=no,menubar=no,status=yes,personalbar=no,titlebar=yes,toolbar=no,width="+this.getWidth()+","+"height="+this.getHeight()+","+"resizable="+(this.isResizable()?"yes":"no")+","+"scrollbars="+(this.isScrollable()?"yes":"no"));if(tc!=null){tc["_jsxwindow"]=this;this._jsxwindow=tc;this._jsxpC=window;return true;}else return false;}};n.close=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){this._jsxwindow.close();return true;}else throw new
Y(jsx3._msg("gui.win.cl",this));};n.focus=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){this._jsxwindow.focus();}else throw new
Y(jsx3._msg("gui.win.cl",this));};n.isOpen=function(){return this._jsxwindow!=null&&!this._jsxwindow.closed;};n.isParentOpen=function(){return this._jsxpC!=null&&!this._jsxpC.closed;};n.moveTo=function(m,q){if(this._jsxwindow!=null&&!this._jsxwindow.closed){if(this._jsxpC!=null&&!this._jsxpC.closed)this._jsxwindow.moveBy(m-this._jsxwindow[a.KM]+this._jsxpC[a.KM],q-this._jsxwindow[a.xP]+this._jsxpC[a.xP]);else this._jsxwindow.moveBy(m-this._jsxwindow[a.KM],q-this._jsxwindow[a.xP]);}else throw new
Y(jsx3._msg("gui.win.cl",this));};n.constrainToScreen=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){var
yb=this._jsxwindow;if(yb[a.KM]<0||yb[a.KM]>window.screen.width||yb[a.xP]<0||yb[a.xP]>window.screen.height)yb.moveTo(0,0);}};n.getOffsetLeft=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){if(this._jsxpC!=null&&!this._jsxpC.closed)return this._jsxwindow[a.KM]-this._jsxpC[a.KM];else return this._jsxwindow[a.KM];}else throw new
Y(jsx3._msg("gui.win.cl",this));};n.getOffsetTop=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed){if(this._jsxpC!=null&&!this._jsxpC.closed)return this._jsxwindow[a.xP]-this._jsxpC[a.xP];else return this._jsxwindow[a.xP];}else throw new
Y(jsx3._msg("gui.win.cl",this));};n.onLoad=function(b){if(Rb.isLoggable(5))Rb.debug("onLoad "+this);var
Hc=b.document;var
Fb=b.opener;var
Xb=Hc.getElementsByTagName("body")[0];var
Jb=Hc.getElementsByTagName("head")[0];var
S=this.getServer().getRootDocument();var
Z=S.getElementsByTagName("link");for(var
U=0;U<Z.length;U++){var
_=Z[U];if(_.rel=="stylesheet"){var
rb=_.getAttribute("href");var
B=Hc.createElement("link");B.setAttribute("id",_.getAttribute("id"));B.setAttribute("href",rb);B.setAttribute("rel",_.getAttribute("rel"));B.setAttribute("type",_.getAttribute("type"));Jb.appendChild(B);}}Xb.innerHTML='<span id="'+this.getRootBlock().getId()+'"></span>';this.getRootBlock().repaint();b["jsx3"]=Fb.jsx3;this._jsxwindow=b;this._jsxpC=Fb;this.setTitle(this.getTitle());this.publish({subject:"open"});};n.onFocus=function(){if(Rb.isLoggable(5))Rb.debug("onFocus "+this);this.publish({subject:"focus"});};n.onBeforeUnload=function(){if(Rb.isLoggable(5))Rb.debug("onBeforeUnload "+this);if(this._jsxwindow!=null){jsx3.gui.Event._deregisterWindow(this._jsxwindow);for(var _b in this._jsxwindow)try{this._jsxwindow[_b]=null;}catch(Kc){}}if(this._jsxpC!=null&&!this._jsxpC.closed)this._jsxpC.focus();this._jsxwindow=null;this._jsxpC=null;this.publish({subject:"close"});};n.onResize=function(){if(Rb.isLoggable(6))Rb.trace("onResize "+this);this.jsxwidth=this._jsxwindow.document.body.clientWidth;this.jsxheight=this._jsxwindow.document.body.clientHeight;if(this._jsxD4!=null)this._jsxwindow.clearTimeout(this._jsxD4);var
rb=this;this._jsxD4=this._jsxwindow.setTimeout(function(){rb._jsxD4=null;jsx3.gui.Painted.Queue.enableChunking(false);rb.getRootBlock().Ch({parentwidth:rb.getWidth(),parentheight:rb.getHeight()},true);jsx3.gui.Painted.Queue.enableChunking(true);},250);this.publish({subject:"resize"});};n.onParentUnload=function(){if(Rb.isLoggable(5))Rb.debug("onParentUnload");this.publish({subject:a.DID_PARENT_CLOSE});};n.getRootBlock=function(){var
yb=this.getChild(0);if(yb==null){yb=new
jsx3.gui.Block(this.getName()+"_JSXROOT",0,0,"100%","100%","");yb.setDynamicProperty("jsxbgcolor","@Solid Light");yb.setRelativePosition(0);yb.setOverflow(2);yb.setIndex(0);this.setChild(yb);}return yb;};n.getWindow=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed)return this._jsxwindow;return null;};n.getParentWindow=function(){if(this._jsxpC!=null&&!this._jsxpC.closed)return this._jsxpC;return null;};n.getDocument=function(){if(this._jsxwindow!=null&&!this._jsxwindow.closed)return this._jsxwindow.document;return null;};n.Ln=function(){return {parentwidth:this.getWidth(),parentheight:this.getHeight()};};n.repaint=function(){return this.getRootBlock().repaint();};n.getWidth=function(){return this.jsxwidth;};n.setWidth=function(p){if(this._jsxwindow!=null&&!this._jsxwindow.closed)this._jsxwindow.resizeBy(p-this.jsxwidth,0);this.jsxwidth=p;};n.getHeight=function(){return this.jsxheight;};n.setHeight=function(m){if(this._jsxwindow!=null&&!this._jsxwindow.closed)this._jsxwindow.resizeBy(0,m-this.jsxheight);this.jsxheight=m;};n.isResizable=function(){return this.jsxresizable;};n.setResizable=function(j){this.jsxresizable=jsx3.Boolean.valueOf(j);};n.isScrollable=function(){return this.jsxscrollable;};n.setScrollable=function(o){this.jsxscrollable=jsx3.Boolean.valueOf(o);};n.isDependent=function(){return this.jsxdependent;};n.setDependent=function(b){this.jsxdependent=jsx3.Boolean.valueOf(b);};n.getTitle=function(){return this.jsxtitle;};n.setTitle=function(c){this.jsxtitle=c;if(this._jsxwindow!=null&&!this._jsxwindow.closed)this._jsxwindow.document.title=c;};n.toString=function(c){return this.jsxsuper()+" "+this.getName();};});
