/*
 * Copyright (c) 2001-2007, TIBCO Software Inc.
 * Use, modification, and distribution subject to terms of license.
 */
jsx3.Class.defineClass("jsx3.app.Monitor",jsx3.util.Logger.FormatHandler,null,function(f,k){var
t=jsx3.app.Server;f._9=false;f.K0=jsx3.net.URIResolver.DEFAULT.resolveURI("jsx:///html/jsx3.app.Monitor.html");f.ideDidLoad=function(){f._9=true;};k.vv=false;k.ZU=true;k.wx=null;k.C_=false;k.mA=null;k.eA=null;k.init=function(p){this.jsxsuper(p);};k.onAfterInit=function(){if(this.wx!=null){var
jb=null;if(jsx3.Class.forName("jsx3.lang.System"))jb=jsx3.System.getApp(this.wx);if(jb!=null){this.GZ(jb);}else t.subscribe(t.EVENT_SERVER_INITED,this,"KW");}else{this.ZU=false;this.C_=false;this.vv=true;this.vt();}};k.GZ=function(c){this.vv=true;this.mA=c;if(this.C_){var
nc=this;c.registerHotKey(function(o){nc.zx();},"m",false,true,true);}else this.vt();};k.KW=function(r){var
sb=r.target;if(sb.getEnv("namespace")==this.wx){if(!f._9||!this.ZU)this.GZ(sb);t.unsubscribe(t.EVENT_SERVER_INITED,this);}};k.handle=function(b){if(this.vv&&(!f._9||!this.ZU))if(this.eA){if(this.eA.closed)if(!this.C_)this.vt();if(!this.eA.closed&&this.eA.appendMessage){var
sc=jsx3.util.strEscapeHTML(this.format(b));this.eA.appendMessage(sc,jsx3.util.Logger.levelAsString(b.getLevel()));}}};k.zx=function(){if(this.eA==null||this.eA.closed)this.vt();};k.vt=function(){this.eA=window.open(f.K0,"Monitor_"+this.getName(),"directories=no,location=no,menubar=no,status=yes,personalbar=no,titlebar=yes,toolbar=no,resizable=yes,scrollbars=no,width=500,height=400");if(this.eA){if(this.mA)if(typeof this.eA.setName=="function")this.eA.setName(this.mA.getEnv("namespace"));else this.eA._jsxname=this.mA.getEnv("namespace");window.focus();}};k.getDisableInIDE=function(){return this.ZU;};k.setDisableInIDE=function(n){this.ZU=n;};k.getServerNamespace=function(){return this.wx;};k.setServerNamespace=function(n){this.wx=n;};k.getActivateOnHotKey=function(){return this.C_;};k.setActivateOnHotKey=function(g){this.C_=g;};});jsx3.util.Logger.Handler.registerHandlerClass(jsx3.app.Monitor.jsxclass);
